### ISSUE TITLE
LightDM autologin doesn't work

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint19.3-beta#30] opened 2019-12-07 10:16 UTC
I made an installation with choosing autologin for the new user.
But at the first boot after the end of the installation, LightDM ask me a password for the user. It shouldn’t.

**Comment by smurphos** [comment] 2019-12-08 07:31
I can't reproduce this for the Cinnamon beta iso. Auto login worked fine on initial boot after installation.

**Comment by InfoLibre** [comment] 2019-12-08 09:49
I have this problem with MATE release.

**Comment by clefebvre** [comment] 2019-12-09 11:44
Are you using home directory encryption? If so, it's normal.. it cannot work in that case.

**Comment by InfoLibre** [comment] 2019-12-09 12:32
No, no encryption.

**Comment by clefebvre** [comment] 2019-12-09 12:53
OK I'll test a new MATE install and try to reproduce it. I successfully tested setting autologin post-install and that worked.

**Comment by clefebvre** [comment] 2019-12-09 13:00
OK so during installation, /target/etc/lightdm/lightdm.conf is successfully created with autologin settings. Upon rebooting the session is opened automatically without issue.

Tested with MATE BETA 64-bit in Virtualbox.

I'll close the issue as we can't reproduce it.

**Closed as completed by clefebvre** 2019-12-09 13:00 UTC
