### ISSUE TITLE
System reports says I need to set a root password even after setting root password.

### ISSUE THREAD

**Issue by joshontech** [linuxmint/mint19.3-beta#39] opened 2019-12-08 19:07 UTC
I clicked on system report applet in the panel and it said I need to set a root password. I do so and reboot and it continues to tell me I need to set root password. The only way to get rid of this is to click "ignore this problem" in the system reports window.

**Comment by clefebvre** [comment] 2019-12-09 11:46
We'll review this. It's working as designed but the design is obviously confusing :)

Closing it here since it's tracked in trello already.

**Closed as completed by clefebvre** 2019-12-09 11:46 UTC
